### ISSUE TITLE
How can I align the dot slides to the right?

### ISSUE THREAD

**Issue by MudarAljundi** [MudarAljundi/trust#1]
This is my progress with the issue so far. I know that the code for adding the footnote slides is here https://github.com/MudarAljundi/trust/blob/gh-pages/js/core/SlideSelect.js

And that the css div class is "dot" at line 510
https://github.com/MudarAljundi/trust/blob/gh-pages/css/slides.css

I haven't figured what to change yet.

Tagging @hamed

This is how it currently looks like
![tag1](https://user-images.githubusercontent.com/13874863/29430930-2989b044-8364-11e7-91c4-7728ad2e05d8.png)

This is what I want. I'd like it aligned to the right like the following
![tag2](https://user-images.githubusercontent.com/13874863/29430941-34e5c388-8364-11e7-833c-dc160ec8f28e.png)

**Comment by hamed** [comment]
This is really simple, just define the direction and language in the html tag and every thing will be right to left. The problem is that the sandbox slide explodes! I fixed that by hand.
This method has one more side effect, -1 will become 1-.
